name: became
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - argparse==1.4.0
      - asttokens==2.4.1
      - backcall==0.2.0
      - cachetools==5.3.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - config==0.5.1
      - configargparse==1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.7
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - executing==2.1.0
      - filelock==3.9.0
      - fonttools==4.47.2
      - fsspec==2023.4.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.28.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.60.1
      - idna==3.4
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lmdb==1.4.1
      - markdown==3.5.2
      - markupsafe==2.1.3
      - matplotlib==3.5.0
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.19.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.3.2
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==1.2.0
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.3.3
      - portalocker==2.8.2
      - prompt-toolkit==3.0.48
      - protobuf==3.20.0
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.18.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch3d==0.3.0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.19.1
      - scikit-learn==1.3.2
      - scipy==1.7.0
      - seaborn==0.11.0
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - setuptools-scm==8.0.4
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==1.9
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tomli==2.0.1
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==1.26.13
      - wandb==0.18.1
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - wget==3.2
      - yacs==0.1.8
      - zipp==3.17.0